---
title: "Sustainability_Labels_PrePreProcessing"
author: "Patrick, Josephine & Niels"
date: "2023-12-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, data.table #bulk CSV uploading)
```

```{r}
# SETTING WORKING DIRECTORY - ONLY ONE THAT NEEDS TO BE CHANGE.
## Change it to the location of bachelor_s_coding folder
knitr::opts_knit$set(root.dir = '/Users/niels/Documents/Bachelor_s_coding/')
setwd("/Users/niels/Documents/Bachelor_s_coding/")
```

# Loading and combining the behavioral data
```{r}
# Pre-processing the Jose behavioral data by combining all the participants into one CSV-file
# Set the path to the directory containing your CSV files
folder_path <- "csv_jose"

# List all CSV files in the directory
all_files <- list.files(path = folder_path, pattern = "\\.csv$")

#adjusting column types
col_types <- cols(
  Date = col_character(),
  ID = col_character(),
  Age = col_double(),
  Gender = col_character(),
  left_stim = col_double(),
  right_stim = col_double(),
  Stimulus = col_double(),
  ReactionTime = col_double()
)

# Read all CSV files and bind them together
data_list <- lapply(all_files, function(file) {
  read_csv(paste0(folder_path,"/", file), col_types = col_types)
})

combined_data <- bind_rows(data_list)

# Write the combined dataframe to a new CSV file
output_J_bev_data <- "Jose_CSV_Beh.csv"   # Update this path for your output location
write_csv(combined_data, output_J_bev_data)
```

# Survey pre-processing
```{r}
##Survey
# Set the path to the directory containing your CSV files
folder_path <- "survey"

# List all CSV files in the directory
all_files <- list.files(path = folder_path, pattern = "\\.csv$")

# Read all CSV files and bind them together
data_list <- lapply(all_files, function(file) {
  read_csv(paste0(folder_path,"/", file))
})

combined_data <- bind_rows(data_list)

# Write the combined dataframe to a new CSV file
output_file <- "final_survey.csv"   # Update this path for your output location
write_csv(combined_data, output_file)
```

```{r}
# Eye-tracking data
jose <- read.csv("/Users/niels/Documents/Bachelor_s_coding/Data_Jose_ED.csv", sep=";")

# Behavioral data
jose_beh <- read.csv("/Users/niels/Documents/Bachelor_s_coding/Jose_CSV_Beh.csv")
```

# CLEANING UP EYE-TRACKING DATA
```{r}
#getting rid of the ID number 14
jose <- jose %>% 
  filter(RECORDING_SESSION_LABEL!=14)

#renaming ID number 15 to 14
jose <- jose %>% 
  mutate(RECORDING_SESSION_LABEL = ifelse(RECORDING_SESSION_LABEL==15, 14, RECORDING_SESSION_LABEL))

#getting rid of the ID number 37
jose <- jose %>% 
  filter(RECORDING_SESSION_LABEL!=37)

# Getting rid of ID number 27, as the data is gone for that participant
jose <- jose %>% 
  filter(RECORDING_SESSION_LABEL != 27)

#renaming trials number 15 to 14
jose <- jose %>% 
  mutate(RECORDING_SESSION_LABEL = ifelse(RECORDING_SESSION_LABEL==38, 37, RECORDING_SESSION_LABEL))

```

# CLEANING UP BEHAVIORAL DATA
```{r}
#getting rid of the trials number 14
jose_beh <- jose_beh %>% 
  filter(ID!=14)

# getting rid of participant 27, as all the data is gone for them
jose_beh <- jose_beh %>% 
  filter(ID!=27)

#renaming trials number 15 to 14
jose_beh <- jose_beh %>% 
  mutate(ID = ifelse(ID==15, 14, ID))

#getting rid of the trials number 14
jose_beh <- jose_beh %>% 
  filter(ID!=37)

#renaming trials number 15 to 14
jose_beh <- jose_beh %>% 
  mutate(ID = ifelse(ID==38, 37, ID))
```

```{r}
# PARTICIPANT 27 DOES NOT CONTAIN ANY DATA. THAT IS WHY IT IS REMOVED.
  group_by(RECORDING_SESSION_LABEL) %>% 
  mutate(TRIAL_INDEX = TRIAL_INDEX - 1) %>% 
  filter(TRIAL_INDEX != 0)
```

```{r}
write_csv(jose_lag, "/Users/niels/Documents/Bachelor_s_coding/Data_Jose_ED_new.csv")
write_csv(jose_beh, "/Users/niels/Documents/Bachelor_s_coding/Jose_CSV_Beh_new.csv")
```

